// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iris_api_issuers.proto

package kz.kase.iris.model;

public final class IrisApiIssuers {
  private IrisApiIssuers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Статус записи с информацией о ценной бумаге. 
   * </pre>
   *
   * Protobuf enum {@code IRIS.IssuerRecordStatus}
   */
  public enum IssuerRecordStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Активная.
     * </pre>
     *
     * <code>IRS_ACTIVE = 0;</code>
     */
    IRS_ACTIVE(0),
    /**
     * <pre>
     * Историческая.
     * </pre>
     *
     * <code>IRS_HISTORY = 1;</code>
     */
    IRS_HISTORY(1),
    /**
     * <pre>
     * Удаленная.
     * </pre>
     *
     * <code>IRS_DELETED = 2;</code>
     */
    IRS_DELETED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Активная.
     * </pre>
     *
     * <code>IRS_ACTIVE = 0;</code>
     */
    public static final int IRS_ACTIVE_VALUE = 0;
    /**
     * <pre>
     * Историческая.
     * </pre>
     *
     * <code>IRS_HISTORY = 1;</code>
     */
    public static final int IRS_HISTORY_VALUE = 1;
    /**
     * <pre>
     * Удаленная.
     * </pre>
     *
     * <code>IRS_DELETED = 2;</code>
     */
    public static final int IRS_DELETED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static IssuerRecordStatus valueOf(int value) {
      return forNumber(value);
    }

    public static IssuerRecordStatus forNumber(int value) {
      switch (value) {
        case 0: return IRS_ACTIVE;
        case 1: return IRS_HISTORY;
        case 2: return IRS_DELETED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<IssuerRecordStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        IssuerRecordStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<IssuerRecordStatus>() {
            public IssuerRecordStatus findValueByNumber(int number) {
              return IssuerRecordStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return kz.kase.iris.model.IrisApiIssuers.getDescriptor().getEnumTypes().get(0);
    }

    private static final IssuerRecordStatus[] VALUES = values();

    public static IssuerRecordStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private IssuerRecordStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:IRIS.IssuerRecordStatus)
  }

  public interface IssuerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IRIS.Issuer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Первичный ключ записи эмитента в &amp;IS_IRIS_Q;.
     * </pre>
     *
     * <code>int32 issuer_id = 1;</code>
     */
    int getIssuerId();

    /**
     * <pre>
     * Код эмитента.
     * </pre>
     *
     * <code>string code = 2;</code>
     */
    java.lang.String getCode();
    /**
     * <pre>
     * Код эмитента.
     * </pre>
     *
     * <code>string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <pre>
     * Статус записи с информацией о эмитенте.
     * </pre>
     *
     * <code>.IRIS.IssuerRecordStatus status = 3;</code>
     */
    int getStatusValue();
    /**
     * <pre>
     * Статус записи с информацией о эмитенте.
     * </pre>
     *
     * <code>.IRIS.IssuerRecordStatus status = 3;</code>
     */
    kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus getStatus();

    /**
     * <pre>
     * Наименование эмитента.
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * Наименование эмитента.
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Внутренняя версия записи в IRIS.
     * </pre>
     *
     * <code>int64 version = 5;</code>
     */
    long getVersion();
  }
  /**
   * <pre>
   * Базовая информация о эмитенте. 
   * </pre>
   *
   * Protobuf type {@code IRIS.Issuer}
   */
  public  static final class Issuer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IRIS.Issuer)
      IssuerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Issuer.newBuilder() to construct.
    private Issuer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Issuer() {
      issuerId_ = 0;
      code_ = "";
      status_ = 0;
      name_ = "";
      version_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Issuer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              issuerId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 40: {

              version_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kz.kase.iris.model.IrisApiIssuers.internal_static_IRIS_Issuer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kz.kase.iris.model.IrisApiIssuers.internal_static_IRIS_Issuer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kz.kase.iris.model.IrisApiIssuers.Issuer.class, kz.kase.iris.model.IrisApiIssuers.Issuer.Builder.class);
    }

    public static final int ISSUER_ID_FIELD_NUMBER = 1;
    private int issuerId_;
    /**
     * <pre>
     * Первичный ключ записи эмитента в &amp;IS_IRIS_Q;.
     * </pre>
     *
     * <code>int32 issuer_id = 1;</code>
     */
    public int getIssuerId() {
      return issuerId_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <pre>
     * Код эмитента.
     * </pre>
     *
     * <code>string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Код эмитента.
     * </pre>
     *
     * <code>string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <pre>
     * Статус записи с информацией о эмитенте.
     * </pre>
     *
     * <code>.IRIS.IssuerRecordStatus status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * Статус записи с информацией о эмитенте.
     * </pre>
     *
     * <code>.IRIS.IssuerRecordStatus status = 3;</code>
     */
    public kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus getStatus() {
      @SuppressWarnings("deprecation")
      kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus result = kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus.valueOf(status_);
      return result == null ? kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus.UNRECOGNIZED : result;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * Наименование эмитента.
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Наименование эмитента.
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private long version_;
    /**
     * <pre>
     * Внутренняя версия записи в IRIS.
     * </pre>
     *
     * <code>int64 version = 5;</code>
     */
    public long getVersion() {
      return version_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (issuerId_ != 0) {
        output.writeInt32(1, issuerId_);
      }
      if (!getCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (status_ != kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus.IRS_ACTIVE.getNumber()) {
        output.writeEnum(3, status_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (version_ != 0L) {
        output.writeInt64(5, version_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (issuerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, issuerId_);
      }
      if (!getCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (status_ != kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus.IRS_ACTIVE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, version_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kz.kase.iris.model.IrisApiIssuers.Issuer)) {
        return super.equals(obj);
      }
      kz.kase.iris.model.IrisApiIssuers.Issuer other = (kz.kase.iris.model.IrisApiIssuers.Issuer) obj;

      boolean result = true;
      result = result && (getIssuerId()
          == other.getIssuerId());
      result = result && getCode()
          .equals(other.getCode());
      result = result && status_ == other.status_;
      result = result && getName()
          .equals(other.getName());
      result = result && (getVersion()
          == other.getVersion());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISSUER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getIssuerId();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kz.kase.iris.model.IrisApiIssuers.Issuer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kz.kase.iris.model.IrisApiIssuers.Issuer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Базовая информация о эмитенте. 
     * </pre>
     *
     * Protobuf type {@code IRIS.Issuer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IRIS.Issuer)
        kz.kase.iris.model.IrisApiIssuers.IssuerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kz.kase.iris.model.IrisApiIssuers.internal_static_IRIS_Issuer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kz.kase.iris.model.IrisApiIssuers.internal_static_IRIS_Issuer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kz.kase.iris.model.IrisApiIssuers.Issuer.class, kz.kase.iris.model.IrisApiIssuers.Issuer.Builder.class);
      }

      // Construct using kz.kase.iris.model.IrisApiIssuers.Issuer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        issuerId_ = 0;

        code_ = "";

        status_ = 0;

        name_ = "";

        version_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kz.kase.iris.model.IrisApiIssuers.internal_static_IRIS_Issuer_descriptor;
      }

      @java.lang.Override
      public kz.kase.iris.model.IrisApiIssuers.Issuer getDefaultInstanceForType() {
        return kz.kase.iris.model.IrisApiIssuers.Issuer.getDefaultInstance();
      }

      @java.lang.Override
      public kz.kase.iris.model.IrisApiIssuers.Issuer build() {
        kz.kase.iris.model.IrisApiIssuers.Issuer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kz.kase.iris.model.IrisApiIssuers.Issuer buildPartial() {
        kz.kase.iris.model.IrisApiIssuers.Issuer result = new kz.kase.iris.model.IrisApiIssuers.Issuer(this);
        result.issuerId_ = issuerId_;
        result.code_ = code_;
        result.status_ = status_;
        result.name_ = name_;
        result.version_ = version_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kz.kase.iris.model.IrisApiIssuers.Issuer) {
          return mergeFrom((kz.kase.iris.model.IrisApiIssuers.Issuer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kz.kase.iris.model.IrisApiIssuers.Issuer other) {
        if (other == kz.kase.iris.model.IrisApiIssuers.Issuer.getDefaultInstance()) return this;
        if (other.getIssuerId() != 0) {
          setIssuerId(other.getIssuerId());
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kz.kase.iris.model.IrisApiIssuers.Issuer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kz.kase.iris.model.IrisApiIssuers.Issuer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int issuerId_ ;
      /**
       * <pre>
       * Первичный ключ записи эмитента в &amp;IS_IRIS_Q;.
       * </pre>
       *
       * <code>int32 issuer_id = 1;</code>
       */
      public int getIssuerId() {
        return issuerId_;
      }
      /**
       * <pre>
       * Первичный ключ записи эмитента в &amp;IS_IRIS_Q;.
       * </pre>
       *
       * <code>int32 issuer_id = 1;</code>
       */
      public Builder setIssuerId(int value) {
        
        issuerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Первичный ключ записи эмитента в &amp;IS_IRIS_Q;.
       * </pre>
       *
       * <code>int32 issuer_id = 1;</code>
       */
      public Builder clearIssuerId() {
        
        issuerId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <pre>
       * Код эмитента.
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Код эмитента.
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Код эмитента.
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Код эмитента.
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Код эмитента.
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        code_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <pre>
       * Статус записи с информацией о эмитенте.
       * </pre>
       *
       * <code>.IRIS.IssuerRecordStatus status = 3;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <pre>
       * Статус записи с информацией о эмитенте.
       * </pre>
       *
       * <code>.IRIS.IssuerRecordStatus status = 3;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Статус записи с информацией о эмитенте.
       * </pre>
       *
       * <code>.IRIS.IssuerRecordStatus status = 3;</code>
       */
      public kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus getStatus() {
        @SuppressWarnings("deprecation")
        kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus result = kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus.valueOf(status_);
        return result == null ? kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Статус записи с информацией о эмитенте.
       * </pre>
       *
       * <code>.IRIS.IssuerRecordStatus status = 3;</code>
       */
      public Builder setStatus(kz.kase.iris.model.IrisApiIssuers.IssuerRecordStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Статус записи с информацией о эмитенте.
       * </pre>
       *
       * <code>.IRIS.IssuerRecordStatus status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * Наименование эмитента.
       * </pre>
       *
       * <code>string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Наименование эмитента.
       * </pre>
       *
       * <code>string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Наименование эмитента.
       * </pre>
       *
       * <code>string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Наименование эмитента.
       * </pre>
       *
       * <code>string name = 4;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Наименование эмитента.
       * </pre>
       *
       * <code>string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long version_ ;
      /**
       * <pre>
       * Внутренняя версия записи в IRIS.
       * </pre>
       *
       * <code>int64 version = 5;</code>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <pre>
       * Внутренняя версия записи в IRIS.
       * </pre>
       *
       * <code>int64 version = 5;</code>
       */
      public Builder setVersion(long value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Внутренняя версия записи в IRIS.
       * </pre>
       *
       * <code>int64 version = 5;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IRIS.Issuer)
    }

    // @@protoc_insertion_point(class_scope:IRIS.Issuer)
    private static final kz.kase.iris.model.IrisApiIssuers.Issuer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kz.kase.iris.model.IrisApiIssuers.Issuer();
    }

    public static kz.kase.iris.model.IrisApiIssuers.Issuer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Issuer>
        PARSER = new com.google.protobuf.AbstractParser<Issuer>() {
      @java.lang.Override
      public Issuer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Issuer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Issuer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Issuer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kz.kase.iris.model.IrisApiIssuers.Issuer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IRIS_Issuer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IRIS_Issuer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026iris_api_issuers.proto\022\004IRIS\"r\n\006Issuer" +
      "\022\021\n\tissuer_id\030\001 \001(\005\022\014\n\004code\030\002 \001(\t\022(\n\006sta" +
      "tus\030\003 \001(\0162\030.IRIS.IssuerRecordStatus\022\014\n\004n" +
      "ame\030\004 \001(\t\022\017\n\007version\030\005 \001(\003*F\n\022IssuerReco" +
      "rdStatus\022\016\n\nIRS_ACTIVE\020\000\022\017\n\013IRS_HISTORY\020" +
      "\001\022\017\n\013IRS_DELETED\020\002B\033\n\022kz.kase.iris.model" +
      "\242\002\004IRISb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IRIS_Issuer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IRIS_Issuer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IRIS_Issuer_descriptor,
        new java.lang.String[] { "IssuerId", "Code", "Status", "Name", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
