package kz.kase.terminal.other

enum class TableType {
    FAVORITE_SHARES,
    FAVORITE_SHARES_ARC,
    FAVORITE_BONDS,
    FAVORITE_BONDS_ARC,

    INDEX_MAIN,
    SHARE_MAIN,
    BONDS_MAIN,
    CURRENCY_MAIN,
    NEWS_MARKET_MAIN,
    NEWS_COMPANY_MAIN,

    SHARES_PAGE,
    SHARES_PAGE_ARC,
    BONDS_PAGE,
    BONDS_PAGE_ARC,

    CURRENCY,
    GS,
    REALTIME,
    INIT,
    DETAILS,

    NEWS_KASE,
    NEWS_MARKET,
    NEWS_OPINION,
    NEWS_MARKET_REVIEW,
    QUOTES,
    UNSET,

    ORDER_SHARE_ACTIVE,
    ORDER_BONDS_ACTIVE,

    DEALS_POSITION_CASH,
    DEALS_POSITION_SHARE,
    DEALS_POSITION_BONDS,
    DEALS_SHARE,
    DEALS_BONDS,
    N_A,
}
